"""Every script that imports ``rhob`` must import it from its OWN checkout.

The failure this prevents is silent, which is what makes it worth a test.

``pip install -e .`` records ONE source tree. A git worktree is a second checkout
sharing that install, so inside a worktree ``import rhob`` resolves to the *other*
tree unless the script puts its own ``src/`` first on ``sys.path``. Nothing errors:
the script runs, imports same-named modules from the wrong tree, and writes results
attributed to the checkout it was launched from. During the 2026 audit remediation a
full leaderboard regeneration was launched this way from a worktree; it failed loudly
only because that worktree happened to contain a module the main checkout lacked
(``rhob.v3.leaderboard.access_summary``). Had the change been to an *existing* module
-- the normal case -- it would have silently published numbers generated by the wrong
source and nobody would have known.

pytest is not exposed to this (``pyproject.toml`` sets ``pythonpath = ["src"]``), so
the test suite passing is not evidence that the scripts are safe. Hence this test.

The required incantation, before the first ``rhob`` import:

    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
"""

from __future__ import annotations

import ast
import pathlib

import pytest

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
_SCRIPTS = sorted((_REPO_ROOT / "scripts").glob("*.py"))


def _imports_rhob(tree: ast.Module) -> bool:
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            if any(a.name == "rhob" or a.name.startswith("rhob.") for a in node.names):
                return True
        elif isinstance(node, ast.ImportFrom):
            mod = node.module or ""
            if mod == "rhob" or mod.startswith("rhob."):
                return True
    return False


def _first_rhob_import_line(tree: ast.Module) -> int | None:
    lines = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            if any(a.name == "rhob" or a.name.startswith("rhob.") for a in node.names):
                lines.append(node.lineno)
        elif isinstance(node, ast.ImportFrom):
            mod = node.module or ""
            if mod == "rhob" or mod.startswith("rhob."):
                lines.append(node.lineno)
    return min(lines) if lines else None


def _bootstrap_lines(tree: ast.Module) -> list[int]:
    """Line numbers of ``sys.path.insert(0, ... / "src")`` calls.

    Matched structurally rather than by string search, so a mention in a docstring or
    comment cannot satisfy the check -- only a real call does.
    """
    found = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        fn = node.func
        if not isinstance(fn, ast.Attribute) or fn.attr != "insert":
            continue
        owner = fn.value
        if not (
            isinstance(owner, ast.Attribute)
            and owner.attr == "path"
            and isinstance(owner.value, ast.Name)
            and owner.value.id == "sys"
        ):
            continue
        # must insert at the FRONT: appending leaves the editable install winning
        if not (node.args and isinstance(node.args[0], ast.Constant) and node.args[0].value == 0):
            continue
        if "src" not in ast.dump(node):
            continue
        found.append(node.lineno)
    return found


_RHOB_SCRIPTS = [
    p for p in _SCRIPTS if _imports_rhob(ast.parse(p.read_text(encoding="utf-8"), filename=str(p)))
]


def test_there_are_scripts_to_check():
    """Guard against the glob silently matching nothing and the suite passing vacuously."""
    assert len(_RHOB_SCRIPTS) >= 10, [p.name for p in _RHOB_SCRIPTS]


@pytest.mark.parametrize("script", _RHOB_SCRIPTS, ids=lambda p: p.name)
def test_script_puts_its_own_src_first(script: pathlib.Path):
    tree = ast.parse(script.read_text(encoding="utf-8"), filename=str(script))
    boots = _bootstrap_lines(tree)
    assert boots, (
        f"{script.name} imports rhob but never runs\n"
        f'    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))\n'
        f"so inside a git worktree it will silently import rhob from the OTHER checkout "
        f"and publish results attributed to this one. See this module's docstring."
    )


@pytest.mark.parametrize("script", _RHOB_SCRIPTS, ids=lambda p: p.name)
def test_bootstrap_precedes_the_first_rhob_import(script: pathlib.Path):
    """Ordering is the whole point -- a correct insert placed after the import is inert."""
    tree = ast.parse(script.read_text(encoding="utf-8"), filename=str(script))
    boots = _bootstrap_lines(tree)
    first = _first_rhob_import_line(tree)
    assert boots and first is not None
    assert min(boots) < first, (
        f"{script.name}: sys.path.insert is at line {min(boots)} but the first rhob "
        f"import is at line {first}. By then the module is already resolved, so the "
        f"insert has no effect."
    )
