"""RHOB interactive leaderboard viewer (Gradio).

A read-only viewer over the committed leaderboard JSON files -- no submission form,
no auth, no write path. Community detector results are submitted via a PR touching
``leaderboard/`` (validated by ``python -m rhob validate``, see
``.github/workflows/leaderboard_validate.yml``), not through this UI. This matches the
project's existing "static files are fine" leaderboard design
(see ``src/rhob/v3/leaderboard/board.py``).

Run locally (from within a full clone of the repo):
    pip install -e ".[space]"
    python space/app.py

When deployed to a Hugging Face Space, only this directory's contents are uploaded
(see .github/workflows/deploy_space.yml), with rhob installed as a regular pip
dependency (space/requirements.txt) rather than imported via a sibling src/ -- and the
deploy step copies leaderboard/*.json alongside this file, so the two candidate
locations below cover "running inside the full repo" and "running as a deployed Space"
respectively.
"""

from __future__ import annotations

import json
from pathlib import Path

import gradio as gr
import pandas as pd

from rhob.v3.leaderboard.adapters import load_any_leaderboard_json
from rhob.v3.leaderboard.board import Leaderboard

_HERE = Path(__file__).resolve().parent
_CANDIDATE_LEADERBOARD_DIRS = [
    _HERE / "leaderboard",  # deployed Space: deploy step copies data alongside app.py
    _HERE.parent / "leaderboard",  # local dev: running from within the full repo clone
]
_LEADERBOARD_DIR = next((d for d in _CANDIDATE_LEADERBOARD_DIRS if d.is_dir()), _CANDIDATE_LEADERBOARD_DIRS[0])

# v5_leaderboard.json is the sole canonical, comprehensive source (all detectors x all
# families, regenerated by scripts/v5_leaderboard_and_transfer.py). An older
# leaderboard.json (pre-v5 format) previously got merged in alongside it here, which
# silently produced duplicate/stale rows for any detector name present in both files --
# the live dashboards showed e.g. two different "Trajectory MLP" rows, one current and
# one a stale ghost with "Cells: 0". v5_leaderboard.json alone is complete; nothing is
# lost by dropping the legacy file. Community submissions (see "How to Submit" below)
# land in a differently-named file and get merged in here explicitly, not silently.
LEADERBOARD_FILES = [
    _LEADERBOARD_DIR / "v5_leaderboard.json",
]
_TRANSFER_FILE = _LEADERBOARD_DIR / "cross_family_transfer.json"

def _n_families_and_detectors() -> tuple[int, int]:
    """Compute the live family/detector counts from the committed leaderboard data,
    rather than hardcoding them -- a hardcoded pair silently goes stale every time a
    new family sub-project ships (caught after the sequence-gen extension shipped:
    the deployed Space kept showing "28" after a regen to 33)."""
    board = _load_combined()
    families: set[str] = set()
    for e in board.entries:
        families.update(e.family_auroc.keys())
    return len(families), len(board.entries)

_CSS = """
@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700;800&family=IBM+Plex+Sans:wght@400;500;600&display=swap');

:root {
    --rhob-bg: #0a0c10;
    --rhob-panel: #12151b;
    --rhob-panel-2: #171b22;
    --rhob-border: #262b35;
    --rhob-text: #dfe4ea;
    --rhob-text-dim: #8891a0;
    --rhob-amber: #ffa93f;
    --rhob-amber-dim: #7a5a2c;
    --rhob-teal: #2ee6b8;
    --rhob-teal-dim: #1c6656;
    --rhob-red: #ff5c66;
}

.gradio-container {
    background: var(--rhob-bg) !important;
    background-image:
        radial-gradient(circle at 15% 0%, rgba(255,169,63,0.06) 0%, transparent 45%),
        radial-gradient(circle at 85% 15%, rgba(46,230,184,0.05) 0%, transparent 40%) !important;
    font-family: 'IBM Plex Sans', sans-serif !important;
    color: var(--rhob-text) !important;
    max-width: 1180px !important;
}

/* ---- Hero header ---- */
#rhob-hero {
    border: 1px solid var(--rhob-border);
    background: linear-gradient(180deg, var(--rhob-panel) 0%, var(--rhob-bg) 100%);
    border-radius: 14px;
    padding: 34px 36px 28px 36px;
    margin-bottom: 22px;
    position: relative;
    overflow: hidden;
}
#rhob-hero::before {
    content: "";
    position: absolute;
    inset: 0;
    background-image: repeating-linear-gradient(
        0deg, rgba(255,255,255,0.015) 0px, rgba(255,255,255,0.015) 1px,
        transparent 1px, transparent 3px
    );
    pointer-events: none;
}
.rhob-eyebrow {
    font-family: 'JetBrains Mono', monospace;
    font-size: 12px;
    letter-spacing: 0.18em;
    text-transform: uppercase;
    color: var(--rhob-amber);
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 10px;
}
.rhob-eyebrow .dot {
    width: 7px; height: 7px; border-radius: 50%;
    background: var(--rhob-teal);
    box-shadow: 0 0 8px 1px var(--rhob-teal);
    animation: rhob-pulse 2.2s ease-in-out infinite;
}
@keyframes rhob-pulse {
    0%, 100% { opacity: 1; transform: scale(1); }
    50% { opacity: 0.45; transform: scale(0.8); }
}
.rhob-title {
    font-family: 'JetBrains Mono', monospace;
    font-weight: 800;
    font-size: 34px;
    letter-spacing: -0.01em;
    color: #f4f6f9;
    margin: 0 0 10px 0;
}
.rhob-title .accent { color: var(--rhob-amber); }
.rhob-sub {
    font-size: 15px;
    line-height: 1.6;
    color: var(--rhob-text-dim);
    max-width: 760px;
    margin-bottom: 18px;
}
.rhob-sub a { color: var(--rhob-teal); text-decoration: none; border-bottom: 1px dotted var(--rhob-teal-dim); }
.rhob-sub a:hover { color: #6ef7d6; }

.rhob-mirrors {
    font-family: 'JetBrains Mono', monospace;
    font-size: 11.5px;
    color: var(--rhob-text-dim);
    letter-spacing: 0.02em;
}
.rhob-mirrors a { color: var(--rhob-text-dim); text-decoration: none; border-bottom: 1px dotted var(--rhob-border); }
.rhob-mirrors a:hover { color: var(--rhob-amber); border-color: var(--rhob-amber); }

/* ---- Stat cards ---- */
#rhob-stats { gap: 14px !important; margin-bottom: 22px !important; }
.rhob-stat {
    border: 1px solid var(--rhob-border);
    background: var(--rhob-panel);
    border-radius: 12px;
    padding: 18px 20px;
    transition: border-color 0.2s ease, transform 0.2s ease;
}
.rhob-stat:hover { border-color: var(--rhob-amber-dim); transform: translateY(-2px); }
.rhob-stat-label {
    font-family: 'JetBrains Mono', monospace;
    font-size: 10.5px;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    color: var(--rhob-text-dim);
    margin-bottom: 6px;
}
.rhob-stat-value {
    font-family: 'JetBrains Mono', monospace;
    font-weight: 700;
    font-size: 28px;
    color: var(--rhob-text);
}
.rhob-stat-value.teal { color: var(--rhob-teal); }
.rhob-stat-value.amber { color: var(--rhob-amber); }
.rhob-stat-note { font-size: 11.5px; color: var(--rhob-text-dim); margin-top: 4px; }

/* ---- RTS table panel ---- */
#rhob-rts-panel {
    border: 1px solid var(--rhob-border);
    background: var(--rhob-panel);
    border-radius: 12px;
    padding: 22px 26px;
    margin-bottom: 22px;
}
#rhob-rts-panel h3 {
    font-family: 'JetBrains Mono', monospace;
    font-size: 15px;
    letter-spacing: 0.02em;
    color: #f4f6f9;
    margin-top: 0;
}
#rhob-rts-panel table { border-collapse: collapse; width: 100%; margin-top: 10px; }
#rhob-rts-panel th {
    font-family: 'JetBrains Mono', monospace;
    font-size: 11px;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: var(--rhob-text-dim);
    text-align: left;
    padding: 8px 10px;
    border-bottom: 1px solid var(--rhob-border);
}
#rhob-rts-panel td {
    font-family: 'JetBrains Mono', monospace;
    font-size: 13.5px;
    padding: 9px 10px;
    border-bottom: 1px solid #1b1f27;
    color: var(--rhob-text);
}
#rhob-rts-panel tr:last-child td { border-bottom: none; }

/* ---- Tabs ---- */
.tab-nav button {
    font-family: 'JetBrains Mono', monospace !important;
    font-size: 13px !important;
    letter-spacing: 0.03em !important;
}

/* ---- Dataframe ---- */
.gradio-container table.table {
    font-family: 'JetBrains Mono', monospace !important;
    font-size: 13px !important;
}
.gradio-container .table-wrap {
    border: 1px solid var(--rhob-border) !important;
    border-radius: 10px !important;
    overflow: hidden !important;
}

/* ---- Dropdowns ---- */
.gradio-container label span { font-family: 'JetBrains Mono', monospace !important; font-size: 11.5px !important; letter-spacing: 0.06em !important; text-transform: uppercase; color: var(--rhob-text-dim) !important; }

footer { display: none !important; }
"""


def _rts_headline() -> tuple[str | None, list[dict]]:
    """Return (best_L2_rts, rows) parsed from the transfer results file."""
    if not _TRANSFER_FILE.exists():
        return None, []
    data = json.loads(_TRANSFER_FILE.read_text())
    rows = []
    best_l2 = None
    for name, r in data.get("results", {}).items():
        rts = r.get("avg_transfer_auroc_mean", r.get("avg_transfer_auroc"))
        level = r.get("access_level", "")
        if rts is None:
            continue
        rows.append({"name": name, "level": level, "rts": rts})
        if level in ("L2", "L3") and (best_l2 is None or rts > best_l2):
            best_l2 = rts
    return best_l2, rows


def _rts_html() -> str:
    """Render the RHOB Transfer Score (RTS) headline table from the transfer results.

    RTS is RHOB's designated headline metric: mean AUROC on the 8 held-out,
    mechanistically-unseen test families, after training only on Families 1-6.
    """
    _, rows = _rts_headline()
    if not rows:
        return ""
    body = ""
    for r in rows:
        rts = r["rts"]
        tag = "chance" if rts < 0.55 else ("near-perfect" if rts > 0.98 else "")
        color = "var(--rhob-red)" if rts < 0.55 else ("var(--rhob-teal)" if rts > 0.9 else "var(--rhob-amber)")
        tag_html = f' <span style="color:{color};font-size:11px;">— {tag}</span>' if tag else ""
        body += (
            f"<tr><td>{r['name']}</td><td>{r['level']}</td>"
            f"<td style='color:{color};font-weight:700;'>{rts:.3f}{tag_html}</td></tr>\n"
        )
    return f"""
    <div id="rhob-rts-panel">
      <h3>THE RHOB TRANSFER SCORE (RTS)</h3>
      <p style="color:var(--rhob-text-dim);font-size:13.5px;line-height:1.6;margin-bottom:0;">
        Train on 6 hacking mechanisms, test on 8 never seen. RTS = mean AUROC on the held-out
        mechanisms — the number every detector submitted to RHOB gets scored on.
      </p>
      <table>
        <tr><th>Detector class</th><th>Access</th><th>RTS (transfer AUROC)</th></tr>
        {body}
      </table>
    </div>
    """


def _load_combined() -> Leaderboard:
    """Load every known leaderboard file, skipping any that don't exist or don't parse."""
    combined = Leaderboard()
    for path in LEADERBOARD_FILES:
        if not path.exists():
            continue
        try:
            board = load_any_leaderboard_json(path)
        except (ValueError, OSError):
            continue
        for entry in board.entries:
            combined.add(entry)
    return combined


def _standings_df(access_level: str, family: str) -> pd.DataFrame:
    board = _load_combined()
    rows = []
    for e in board.standings():
        if access_level != "All" and e.access_level != access_level:
            continue
        family_score = e.family_auroc.get(family) if family != "All" else None
        rows.append(
            {
                "Detector": e.detector_name,
                "Access Level": e.access_level,
                "Overall AUROC": round(e.overall_auroc, 3) if e.overall_auroc is not None else "-",
                f"{family} AUROC" if family != "All" else "": (
                    round(family_score, 3) if family_score is not None else "-"
                ) if family != "All" else "",
                "Cells": e.n_cells,
                "Author": e.author,
            }
        )
    df = pd.DataFrame(rows)
    if family == "All" and "" in df.columns:
        df = df.drop(columns=[""])
    return df


def _all_families() -> list[str]:
    board = _load_combined()
    families: set[str] = set()
    for e in board.entries:
        families.update(e.family_auroc.keys())
    return ["All"] + sorted(families)


def _all_access_levels() -> list[str]:
    return ["All", "L0", "L1", "L2", "L3"]


def _stat_card(label: str, value: str, note: str = "", color_class: str = "") -> str:
    return f"""
    <div class="rhob-stat">
      <div class="rhob-stat-label">{label}</div>
      <div class="rhob-stat-value {color_class}">{value}</div>
      <div class="rhob-stat-note">{note}</div>
    </div>
    """


_theme = gr.themes.Base(
    font=[gr.themes.GoogleFont("IBM Plex Sans"), "sans-serif"],
    font_mono=[gr.themes.GoogleFont("JetBrains Mono"), "monospace"],
).set(
    body_background_fill="#0a0c10",
    body_text_color="#dfe4ea",
    background_fill_primary="#12151b",
    background_fill_secondary="#171b22",
    border_color_primary="#262b35",
    block_background_fill="#12151b",
    block_border_color="#262b35",
    block_label_text_color="#8891a0",
    button_primary_background_fill="#ffa93f",
    button_primary_text_color="#0a0c10",
)

with gr.Blocks(title="RHOB Leaderboard") as demo:
    best_rts, _ = _rts_headline()
    best_rts_str = f"{best_rts:.3f}" if best_rts is not None else "—"

    gr.HTML(
        f"""
        <div id="rhob-hero">
          <div class="rhob-eyebrow"><span class="dot"></span>LIVE · REWARD-HACKING ONSET BENCHMARK</div>
          <div class="rhob-title">RHOB <span class="accent">/</span> Leaderboard</div>
          <div class="rhob-sub">
            Read-only viewer over the committed leaderboard data in this repository.
            See the <a href="https://github.com/Aarav500/rhob/blob/main/docs/TUTORIAL_DETECTOR.md" target="_blank">Detector Tutorial</a>
            for how to evaluate your own detector, and the <b>How to Submit</b> tab below for how results get added here.
          </div>
          <div class="rhob-mirrors">
            MIRRORS &nbsp;
            <a href="https://huggingface.co/spaces/Aarav500/rhob-leaderboard" target="_blank">hf space</a> &nbsp;·&nbsp;
            <a href="http://54.208.200.139/" target="_blank">aws ec2</a> &nbsp;·&nbsp;
            <a href="https://rhob.aarav-shah.com/" target="_blank">rhob.aarav-shah.com</a>
          </div>
        </div>
        """
    )

    n_families, n_detectors = _n_families_and_detectors()
    with gr.Row(elem_id="rhob-stats"):
        gr.HTML(_stat_card("Families", str(n_families), "matched proxy/legit pairs"))
        gr.HTML(_stat_card("Detectors", str(n_detectors), "L0 reward-only → L3 oracle"))
        gr.HTML(_stat_card("Best RTS", best_rts_str, "transfer AUROC, held-out mechanisms", "teal"))
        gr.HTML(_stat_card("Complexity tiers", "5", "tabular → multi-agent", "amber"))

    _rts_text = _rts_html()
    if _rts_text:
        gr.HTML(_rts_text)

    with gr.Tab("Standings"):
        with gr.Row():
            access_dropdown = gr.Dropdown(
                choices=_all_access_levels(), value="All", label="Access Level"
            )
            family_dropdown = gr.Dropdown(
                choices=_all_families(), value="All", label="Family"
            )
        table = gr.Dataframe(value=_standings_df("All", "All"), interactive=False)

        def _refresh(access_level, family):
            return _standings_df(access_level, family)

        access_dropdown.change(_refresh, [access_dropdown, family_dropdown], table)
        family_dropdown.change(_refresh, [access_dropdown, family_dropdown], table)

    with gr.Tab("How to Submit"):
        gr.Markdown(
            """
## Submitting a Detector Result

This viewer is read-only by design (no auth, no write path -- see
`src/rhob/v3/leaderboard/board.py`'s "static files are fine" approach). To get a result
included here:

1. Evaluate your detector: `python -m rhob evaluate --detector your_detector.py`
2. Validate the submission: `python -m rhob validate submission.json`
3. Open a PR adding your submission under `leaderboard/`, or run
   `python -m rhob submit submission.json` to merge it into the tracked leaderboard
   files locally before committing.

A CI workflow (`.github/workflows/leaderboard_validate.yml`) automatically validates
any submission JSON added in a PR.

See [CONTRIBUTING.md](https://github.com/Aarav500/rhob/blob/main/CONTRIBUTING.md) for
the full admission-gate requirements if you're also proposing a new family.
"""
        )


if __name__ == "__main__":
    demo.launch(css=_CSS, theme=_theme)
