#!/usr/bin/env python3
"""Render a coding sheet to a markdown findings table.

Follows the same shape as ``scripts/admission_ledger.py``: a JSON coding sheet is
the source of truth, this renders the human-readable artifact beside it, and the
artifact is committed so a reader does not have to run anything to check it.

    python scripts/audit_table.py                    # -> audit/SELF_CODING.md
    python scripts/audit_table.py path/to/sheet.json

Rows that are not admissible are printed rather than dropped, because "we did not
score these and here is why" is part of the result.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from rhob.audit import format_table, load_coding, run_survey  # noqa: E402

DEFAULT_SHEET = REPO / "audit" / "rhob_self_coding.json"

_PREAMBLE = """# Falsifiability coding: findings table

Generated by `scripts/audit_table.py` from `{sheet}`. Do not edit by hand.

The decision rules a coder applied to produce the source rows are in
[docs/SURVEY_PROTOCOL.md](../docs/SURVEY_PROTOCOL.md). The verdicts are produced by
`rhob.audit.diagnostics`.

**`undemonstrated` is the mildest verdict and does not mean a check cannot fail.** It
means nothing published shows it returning a negative. See §7 of the protocol for what
this coding cannot conclude.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sheet", nargs="?", default=str(DEFAULT_SHEET))
    parser.add_argument("-o", "--out", default=None)
    args = parser.parse_args()

    sheet = Path(args.sheet)
    out = Path(args.out) if args.out else sheet.with_name("SELF_CODING.md")

    snapshots = load_coding(sheet)
    parts = [_PREAMBLE.format(sheet=sheet.relative_to(REPO))]

    for name, rows in snapshots.items():
        result = run_survey(rows)
        parts.append(f"\n## `{name}`\n")
        parts.append(format_table(result))

        for skipped in result.skipped:
            parts.append(
                f"\n- **not scored** `{skipped.criterion.criterion}`: {skipped.why}"
            )
        parts.append("")

    out.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(REPO)}")

    for name, rows in snapshots.items():
        result = run_survey(rows)
        n_inv, n_eq = result.inverted_rate()
        print(f"  {name}: {n_inv}/{n_eq} equivalence-shaped criteria inverted, "
              f"{len(result.undemonstrated)} undemonstrated, "
              f"{len(result.skipped)} not scored")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
